name: Publish packages to PyPI

on:
  push:
    branches: [rust]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.post[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  binary-wheels:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-latest
    runs-on: ${{ matrix.os }}
    environment: release
    steps:
    - uses: actions/checkout@v6
    - name: Install the Rust toolchain
      uses: actions-rs/toolchain@v1
      if: runner.os == 'Windows'
      with:
        toolchain: stable
    - name: Build wheels
      uses: pypa/cibuildwheel@v3.3
      env:
        CIBW_SKIP: "*t-*"
        CIBW_ARCHS: "auto64"
        CIBW_TEST_GROUPS: "test"
        CIBW_TEST_COMMAND: "python -m pytest {project}/tests"
        # Install Rust in cibuildwheel environments
        CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
        CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"
        CIBW_BEFORE_ALL_MACOS: curl -sSf https://sh.rustup.rs | sh -s -- -y
        CIBW_ENVIRONMENT_MACOS: "PATH=$HOME/.cargo/bin:$PATH"
    - uses: actions/upload-artifact@v6
      with:
        name: wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  wasi-wheel:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust with WASI target
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add wasm32-wasip1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install maturin
        run: pip install maturin

      - name: Build WASI wheel
        run: |
          maturin build \
            --target wasm32-wasip1 \
            -m rust/Cargo.toml \
            -i python3.11
            --release \
            --out dist

      - uses: actions/upload-artifact@v6
        with:
          name: wasi-wheel
          path: dist/*.whl

  sdist:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install build
    - name: Create the sdist
      run: python -m build -s .
    - uses: actions/upload-artifact@v6
      with:
        name: sdist
        path: dist/*

  publish:
    needs:
      - binary-wheels
      - sdist
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Download the sdist and binary wheels
      uses: actions/download-artifact@v7
      with:
        merge-multiple: true
        path: dist
    - name: Move the packages to dist/
      run: |
        mkdir dist
        mv */*.whl */*.tar.gz dist
        tree
#    - name: Upload packages
#      uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: Create a GitHub release
    needs:
      - binary-wheels
      - wasi-wheel
      - sdist
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: Download the pyodide wheel
      uses: actions/download-artifact@v7
      with:
        name: wasi-wheel
        path: dist
    - id: changelog
      uses: agronholm/release-notes@v1
      with:
        path: docs/versionhistory.rst
    - uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        allowUpdates: true
        artifacts: dist/*.whl
        artifactErrorsFailBuild: true
        draft: true
        skipIfReleaseExists: true
        tag: 6.0.0
